window.BANK = window.BANK || {};
window.BANK.reading = [
  {src:"真题",y:"2024.6",title:"社交媒体与青少年即时通讯",skillNote:"真题来源：新东方在线；考查细节定位与推理",passage:"There is plenty of complaints about how social media--texting in particular--may be harming children's social and intellectual development. But a new study suggests that constant instant messaging (IM'ing) and texting among teens may also provide benefits, particularly for those who are introverted.\n\nBritish researchers studied instant messages exchanged by 231 teens, aged 14 to 18. All of the participants were regular or extensive IM'ers. In the U.S., two thirds of teens use instant messaging services regularly, with a full third messaging at least once every day.\n\nThe researchers analyzed 150 conversations in the study, and reported the results in the journal Computers in Human Behavior. In 100 of these chats, the study participant began IM'ing while in a negative emotional state such as sadness, distress or anger. The rest were conversations begun when the participant was feeling good or neutral. After the chat, participants reported about a 20% reduction in their distress--not enough to completely eliminate it, but enough to leave them feeling better than they had before reaching out.\n\nOur findings suggest that IM'ing between distressed adolescents and their peers may provide emotional relief and consequently contribute to their well-being, the authors write, noting that prior research has shown that people assigned to talk to a stranger either in real life or online improved their mood in both settings, but even more with IM. And people who talk with their real-life friends online also report feeling closer to them than those who just communicate face-to-face, implying a strengthening of their bond.\n\nWhy would digital communication trump human contact? The reasons are complex, but may have something to do with the fact that users can control expression of sadness and other emotions via IM without revealing emotional elements like tears that some may perceive as embarrassing or sources of discomfort. Studies also show that the anonymity of writing on a device blankets the users in a sense of safety that may prompt people to feel more comfortable in sharing and discussing their deepest and most authentic feelings.",
   questions:[
    {q:"What is the finding of the new study by British researchers?",opts:["Instant messaging will hinder children's social and intellectual development.","Introverted teens may benefit from constant instant messaging.","Two thirds of American teens use instant messaging every day.","American teens aged 14 to 18 are extensive instant messaging users."],a:1,skill:"细节-研究发现",ex:"定位句指出经常性即时通讯对内向青少年可能有正面效应，故选B。",ref:["may also provide benefits, particularly for those who are introverted"]},
    {q:"What can be inferred from the results of the study?",opts:["Teens are more likely to send instant messages when feeling distressed.","Instant messaging can help completely remove teens' negative emotions.","Chat via instant messaging services makes participants feel good or calm.","Constant instant messaging can help teens control their negative emotions."],a:0,skill:"推理判断",ex:"100条对话显示研究对象在消极情绪中开始聊天，可推断情绪低落时更倾向发消息，选A。",ref:["began IM'ing while in a negative emotional state"]},
    {q:"According to the authors of Computers in Human Behavior,",opts:["talking to strangers on the Internet can improve the mood","face-to-face talk can strengthen the bond between friends","people often feel closer to real-life friends than to net friends","teens feeling bad can benefit from talks via instant messaging"],a:3,skill:"细节-研究结论",ex:"研究者指出心情不好的青少年可获益于即时通讯聊天，选D。",ref:["distressed adolescents and their peers may provide emotional relief"]},
    {q:"What does the digital communication enable users to do?",opts:["Avoid embarrassment and discomfort.","Share and discuss more information.","Produce more expressive writings.","Find more sympathetic friends."],a:0,skill:"细节-功能",ex:"数字通讯可隐藏令人尴尬的情绪元素，选A。",ref:["without revealing emotional elements like tears that some may perceive as embarrassing"]},
    {q:"What does Susan Cain say about introverts?",opts:["They do not reveal their thoughts to friends, family and colleagues.","They tend to feel more distressed about IM conversations than extraverts.","They are more skillful at the art of socializing than extraverts.","They at times desire to socialize or talk via social media."],a:3,skill:"细节-观点",ex:"即使社交能力最强的内向者有时也渴望社交或打电话应对自如，选D。",ref:["Susan Cain"]}
   ]},
  {src:"真题",y:"2023.6",title:"可再生能源（单题精练）",skillNote:"考查推理判断：识别支持与质疑两方面",passage:"The use of renewable energy sources has been a hot topic in recent years. While many experts argue that renewable energy is the key to solving the world's energy crisis, others remain skeptical about its feasibility. Some critics point out that renewable energy sources, such as solar and wind power, are often unreliable and expensive to maintain. However, proponents of renewable energy argue that the long-term benefits outweigh the initial costs.",
   questions:[
    {q:"What can be inferred from the passage about renewable energy?",opts:["Renewable energy is becoming less popular.","Renewable energy is beneficial for all companies.","Renewable energy presents both opportunities and challenges.","Renewable energy is the only solution for increasing productivity."],a:2,skill:"推理判断",ex:"文章既提到好处也提到挑战（不可靠、昂贵），故选C。",ref:["others remain skeptical about its feasibility","are often unreliable and expensive to maintain","the long-term benefits outweigh the initial costs"]}
   ]},
  {src:"真题",y:"2024.12",title:"远程办公（单题精练）",skillNote:"考查细节定位+同义替换：hesitate↔weaken",passage:"Although remote work improves individual efficiency, corporate managers worry that full-time remote arrangements will hinder spontaneous communication among employees, thereby weakening team creativity and cooperative efficiency.",
   questions:[
    {q:"Why do many companies hesitate to adopt remote working policies fully?",opts:["They fear it will weaken team collaboration and innovation.","They lack technical support for offline management.","They are worried about rising operational costs.","They have no experience in flexible working management."],a:0,skill:"细节-同义替换",ex:"原文 weaken team creativity and cooperative efficiency 对应A的 weaken team collaboration and innovation，选A。",ref:["weakening team creativity and cooperative efficiency"]}
   ]},
  {src:"真题",y:"2023.6",title:"弹性工作制（单题精练）",skillNote:"考查词汇/句式替换：prefer↔favored by",passage:"Most employees prefer flexible working hours because it allows them to balance work and family life.",
   questions:[
    {q:"Which of the following best restates the sentence?",opts:["Flexible working hours are favored by most employees for work-family balance.","Most employees refuse flexible working hours due to family pressure.","Flexible working hours reduce employees' productivity at home.","Employers force employees to adopt flexible working hours."],a:0,skill:"细节-同义替换",ex:"prefer 与 are favored by 替换，allows them to balance work and family life 与 for work-family balance 替换，选A。",ref:["prefer flexible working hours because it allows them to balance work and family life"]}
   ]},
  {src:"真题",y:"2024.6",title:"社交媒体与阅读能力（单题精练）",skillNote:"考查同义替换：overuse↔excessive use",passage:"The study points out that the overuse of social media and short-video platforms is the primary cause of the decline in young people's reading ability, as it reduces their attention span and patience for long texts.",
   questions:[
    {q:"What is the main reason for young people's poor reading ability according to the study?",opts:["The lack of school libraries in rural areas.","The excessive use of social media and short-video platforms.","The high cost of printed books.","The decline of traditional newspapers."],a:1,skill:"细节-同义替换",ex:"overuse 对应 excessive use，primary cause 对应 main reason，选B。",ref:["the overuse of social media and short-video platforms is the primary cause of the decline"]}
   ]},
  {src:"模拟",y:"—",title:"模拟阅读（科普·人工智能）",skillNote:"自编模拟题，用于补充练习量",passage:"Artificial intelligence is reshaping the job market at a speed few predicted. A 2024 report by a global consultancy found that nearly 40% of routine office tasks could be automated within a decade. Yet the same report stressed that AI is more likely to augment human work than replace it entirely. Companies that invest in retraining their employees tend to see higher productivity and lower turnover. Critics warn, however, that without proper regulation, the benefits of AI may concentrate among a small group of tech giants, widening the gap between skilled and unskilled workers.",
   questions:[
    {q:"What did the 2024 consultancy report find about AI?",opts:["AI will completely replace all office workers.","About 40% of routine office tasks may be automated in a decade.","AI reduces company productivity.","Most countries have banned AI in offices."],a:1,skill:"细节-数字",ex:"报告指近40%常规办公任务十年内可能自动化，选B。",ref:["nearly 40% of routine office tasks could be automated within a decade"]},
    {q:"What is the report's view on AI and human work?",opts:["AI will replace humans entirely.","AI is more likely to augment than replace human work.","AI has no effect on productivity.","Human work is obsolete."],a:1,skill:"细节-观点",ex:"报告强调AI更可能增强而非完全替代人类工作，选B。",ref:["AI is more likely to augment human work than replace it entirely"]},
    {q:"What advantage do companies investing in retraining gain?",opts:["Higher productivity and lower turnover.","Lower taxes.","Fewer employees.","No need for regulation."],a:0,skill:"细节-因果",ex:"投资再培训的公司生产率更高、流失率更低，选A。",ref:["invest in retraining their employees tend to see higher productivity and lower turnover"]},
    {q:"What do critics warn about?",opts:["AI will disappear soon.","Benefits may concentrate among tech giants, widening inequality.","All workers will become skilled.","Regulation is unnecessary."],a:1,skill:"态度-担忧",ex:"批评者警告缺乏监管会使收益集中、扩大差距，选B。",ref:["the benefits of AI may concentrate among a small group of tech giants"]},
    {q:"What is the author's overall tone?",opts:["Totally pessimistic.","Uncritical praise.","Balanced and cautious.","Indifferent."],a:2,skill:"主旨-态度",ex:"既讲机遇也讲风险，语气平衡审慎，选C。",ref:["Yet the same report stressed","Critics warn, however"]}
   ]},
  {src:"模拟",y:"—",title:"模拟阅读（社会·老龄化）",skillNote:"自编模拟题，用于补充练习量",passage:"As populations age across the developed world, the question of how to care for the elderly has moved to the center of policy debate. Traditional family-based care is weakening as younger generations migrate to cities and women join the workforce. In response, many governments are promoting community-based care and smart monitoring devices that allow the elderly to live independently longer. A pilot program in one Asian city reduced hospital admissions among participants by 22% within a year. Still, experts caution that technology cannot replace human companionship, and that emotional support remains essential.",
   questions:[
    {q:"Why is family-based care weakening?",opts:["Younger people move to cities and women work.","The elderly refuse family care.","Governments banned it.","It is too expensive."],a:0,skill:"细节-因果",ex:"年轻一代进城、女性就业导致家庭养老弱化，选A。",ref:["Traditional family-based care is weakening as younger generations migrate to cities and women join the workforce"]},
    {q:"What solution do governments promote?",opts:["Sending the elderly abroad.","Community-based care and smart monitoring.","Eliminating pensions.","Forcing families to care."],a:1,skill:"细节-措施",ex:"政府推广社区养老与智能监测，选B。",ref:["many governments are promoting community-based care and smart monitoring devices"]},
    {q:"What result did the pilot program show?",opts:["Admissions rose by 22%.","Admissions fell by 22%.","No change.","Costs doubled."],a:1,skill:"细节-数字",ex:"试点使住院率下降22%，选B。",ref:["reduced hospital admissions among participants by 22%"]},
    {q:"What do experts caution?",opts:["Technology replaces companionship.","Emotional support is still essential.","The elderly dislike devices.","Cities should shrink."],a:1,skill:"态度-提醒",ex:"专家提醒技术无法替代陪伴，情感支持仍必要，选B。",ref:["technology cannot replace human companionship, and that emotional support remains essential"]},
    {q:"What is the main idea?",opts:["Aging is a disaster.","Tech alone solves elderly care.","A mixed approach to elderly care is needed.","Families should disappear."],a:2,skill:"主旨-概括",ex:"文章主张社区+科技+人情味的综合养老，选C。",ref:["how to care for the elderly has moved to the center","governments are promoting community-based care","technology cannot replace human companionship"]}
   ]}
];
