window.BANK = window.BANK || {};
window.BANK.listening = [
  {src:"真题",y:"2025.6",title:"长对话·时装系列（原文跟读+自测）",note:"说明：六级听力需配合音频训练，此处提供真题原文供跟读与题目自测；点击“显示参考答案与解析”核对。",transcript:"M: Thanks for meeting me. I wanted to discuss her latest collection before the show.\nW: Of course. This season I tried to move away from strict social norms and instead incorporate something slightly absurd into my aesthetic. Rather than following public expectations, I merged styles often at opposite ends of the fashion spectrum.\nM: That is a bold move. Did the indigenous elements help?\nW: Absolutely. The incorporation of indigenous aspects, along with my underlying signature touch, made this collection a statement of the season.\nM: You have proven yourself a formidable young designer. What are you looking forward to next?\nW: Seeing how the public receives these creations, and then pushing further.",
   questions:[
    {q:"What are the speakers mainly talking about?",opts:["The private label L'Orange.","The woman's latest collection.","This season's new fashion trend.","The head designer's role."],a:1,ex:"对话围绕女士最新时装系列展开，选B。",ref:["discuss her latest collection before the show"]},
    {q:"What does the woman say she always tries to incorporate into her aesthetic?",opts:["Something reflecting social norms.","Something meeting public expectations.","Something slightly absurd.","Something a bit ambiguous."],a:2,ex:"女士明确说融入略带荒诞的元素，选C。",ref:["incorporate something slightly absurd into my aesthetic"]},
    {q:"What does the woman say she likes to do?",opts:["Follow public expectations strictly.","Merge styles at opposite ends of the fashion spectrum.","Avoid indigenous elements.","Copy other designers."],a:1,ex:"女士说把截然相反的风格融合，选B（自测题，原文对应 merging styles at opposite ends）。",ref:["merged styles often at opposite ends of the fashion spectrum"]},
    {q:"What is the man looking forward to?",opts:["The woman's new creations.","A business partnership.","A fashion award.","Retiring from design."],a:0,ex:"男士说迫不及待想看女士接下来的作品，选A（自测题）。",ref:["What are you looking forward to next","Seeing how the public receives these creations"]}
   ]},
  {src:"真题",y:"2025.6",title:"长对话·法律职业（原文跟读+自测）",note:"说明：真题原文跟读练习；答案见“参考答案与解析”。",transcript:"A: Have you given more thought to studying law?\nB: I've been thinking about it a lot. In fact, this is why I wished to speak to you. I wanted to hear more about what it's like.\nA: A career in law is a beautiful thing. Many people say it's boring, but I disagree. There are many different branches of law and many different jobs.\nB: You are involved with buildings and construction, right?\nA: Correct. I'm a solicitor specializing in real estate. Most of my work involves mediating land disputes.\nB: Could you give me an example?\nA: Sure. I am often employed to arbitrate between two clashing parties.",
   questions:[
    {q:"What does B want to know from A?",opts:["How to build houses.","What a career in law is like.","Where A works.","Why A is bored."],a:1,ex:"B说想多了解学法律是怎么回事，选B（自测题）。",ref:["wanted to hear more about what it's like"]},
    {q:"What is A's attitude toward a law career?",opts:["Boring.","Beautiful and worthwhile.","Too difficult.","Not for B."],a:1,ex:"A说法律职业是美好的，选B（自测题）。",ref:["A career in law is a beautiful thing"]},
    {q:"What does A specialize in?",opts:["Real estate law.","Criminal law.","Tax law.","Family law."],a:0,ex:"A说专攻房地产法律，选A（自测题）。",ref:["a solicitor specializing in real estate"]},
    {q:"What does A often do in his work?",opts:["Build houses.","Arbitrate between clashing parties.","Teach students.","Write novels."],a:1,ex:"A说常被请去为冲突双方仲裁，选B（自测题）。",ref:["often employed to arbitrate between two clashing parties"]}
   ]}
];
